routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\Companys\CompanyEmployeesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('employee', [CompanyEmployeesController::class, 'index'])->where('employee', '[0-9]+')->name('employee.index');
Route::get('employee/create', [CompanyEmployeesController::class, 'create'])->where('employee', '[0-9]+')->name('employee.create');
Route::post('employee', [CompanyEmployeesController::class, 'store'])->where('employee', '[0-9]+')->name('employee.store');
Route::get('employee/{employee}/edit', [CompanyEmployeesController::class, 'edit'])->where('employee', '[0-9]+')->name('employee.edit');
Route::put('employee', [CompanyEmployeesController::class, 'update'])->where('employee', '[0-9]+')->name('employee.update');

Route::prefix('companys')->middleware('auth')->name('admin.companys.')->group(base_path('routes/web/companys.php'));

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function employee()
    {
        return $this->hasOne(\App\Models\CompanyEmployee::class);
    }

}

app/Http/Controllers/Admin/Companys/CompanyEmployeesController.php
<?php

namespace App\Http\Controllers\Admin\Companys;

use App\Models\Company;
use App\Models\CompanyEmployee;
use App\Http\Controllers\Controller;
use App\Http\Requests\Companys\Employee\StoreEmployeeRequest;
use App\Http\Requests\Companys\Employee\UpdateEmployeeRequest;
use App\Models\Employee;

class CompanyEmployeesController extends Controller
{
    public function index(Company $company,Employee $employee)
    {
        $employee = Employee::all();
        return view('admin.companys.employee.index', compact('company', 'employee'));
    }

    // public function show(Company $company)
    // {
    //     $company = Company::where('company_id', $company)->first();
    //     return view('admin.companys.employee.index')->with($company);
    //     // return $company->load('admin');
    // }

    public function create(Company $company, Employee $employee)
    {
        return view('admin.companys.Employee.create', compact('company', 'employee'));
    }

    public function store(StoreEmployeeRequest $request, Company $company, Employee $employee)
    {
        // $validated = $request->validate([
        //     'first_name'=> 'required',
        //     'last_name'=> 'required',
        //     'company'=> 'required|digits:6|numeric',
        //     'email'=> 'required',
        //     'phone'=> 'required'
        // ]);

        // Employee::create([
        //     'first_name'=> $request->first_name,
        //     'last_name'=> $request->last_name,
        //     'company'=> $request->company,
        //     'email'=> $request->email,
        //     'phone'=> $request->phone
        // ]);

        // return redirect()->route('employee.index')->with('success', 'Successfully created a new Employee in Company!');

        $employee = Employee::create($request->only('first_name', 'last_name','company', 'email', 'phone'));
        // $company = Company::create($company->id, $request->validated());

        return redirect()->route('employee.index', $employee->id)->with('success', 'Successfully created a new Employee in Company!');
    }

    public function update(UpdateEmployeeRequest $request, Company $company)
    {
        $company->employee->update($request->validated());

        return redirect()->route('admin.companys.employee.index', $company->id)->with('success', 'Successfully updated company Employee details!');
    }
}

app/Http/Controllers/Admin/Companys/CompanysController.php
<?php

namespace App\Http\Controllers\Admin\Companys;

use App\Models\Company;
use Illuminate\Pagination;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\Companys\StoreCompanyRequest;
use App\Http\Requests\Companys\UpdateCompanyRequest;
use App\Http\Requests\Companys\UpdateProfileImageRequest;

class CompanysController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('admin.companys.index', ['companys' => Company::latest()->simplePaginate(10)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.companys.create');


        $company = Company::create();
        Mail::send('emails.Mail',$company->toArray(),
        function($message){
            $message->to('c3c5d113f6-7ae32f@inbox.mailtrap.io', 'Mail Trap')
            ->subject('Company Create Subject');
        });
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCompanyRequest $request)
    {
        $company = Company::create($request->only('name', 'email', 'website'));

        if ($request->hasFile('logo')) {
            $path = $request->logo->store('public/company/logo');
            $company->update(['logo' => $path]);
        }
        return redirect()->route('admin.companys.dashboard', $company->id)->with('success', 'Successfully Created a New company');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        return $company->load('employee');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('admin.companys.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCompanyRequest $request, Company $company)
    {
        $company->update($request->validated());

        return back()->with('success', 'Successfully updated company details!');
    }

    public function updateProfileImage(UpdateProfileImageRequest $request, Company $company)
    {
        if ($company->logo) {
            Storage::delete($company->logo);
        }
        $path = $request->image->store('public/company/logo');

        $company->update(['logo' => $path]);

        return back()->with('success', 'Successfully updated profile image');
    }

    public function destroyProfileImage(Company $company)
    {
        if ($company->logo) {
            Storage::delete($company->logo);

            $company->update(['logo' => null]);
        }

        return back()->with('success', 'Successfully deleted profile image!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        if ($company->logo) {
            Storage::delete($company->logo);
        }

        $company->delete();

        return redirect()->route('admin.companys.dashboard')->with('success', 'Successfully deleted company and all assets related to them.');
    }
}

resources/views/admin/companys/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="card mt-3">
            <div class="card-body">
                <div class="d-flex">
                    <h1>{{__('Create Company')}}</h1>

                    <div class="ml-auto">
                        <div class="dropdown">
                            <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{__('Actions')}}
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                              <a class="dropdown-item" href="{{ route('admin.companys.dashboard') }}">{{__('Home')}}</a>
                            </div>
                        </div>
                    </div>
                </div>

                <hr>
                @if ($errors->count())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $message)
                                <li>{{ $message }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif



                <form action="{{ route('admin.companys.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group">
                        <label for="name" style="font-family:Arial; opacity:85%; color:rgba(170, 170, 170, 0.925);">{{__('Name')}}</label>
                        <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" placeholder="{{__('Insert Name')}}" style="font-family:Arial; opacity:85%;" value="{{ old('name')}}">
                        @error('name')
                        <div id="validationServerUsernameFeedback" class="invalid-feedback" style="font-size:15px">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="email" style="font-family:Arial; opacity:90%; color:rgba(170, 170, 170, 0.925);">{{__('Email')}}</label>
                        <input type="email" name="email" id="email" class="form-control @error('email') is-invalid @enderror" placeholder="{{__('Insert Email')}}" style="font-family:Arial; opacity:85%;" value="{{ old('Email')}}">
                        @error('email')
                        <div id="validationServerUsernameFeedback" class="invalid-feedback" style="font-size:15px">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="">{{__('Image')}}</label>
                        <input type="file" class="form-control-file btn-light" id="logo "alt="Image Failed to Load">
                        @error('logo')
                        <div id="validationServerUsernameFeedback" class="invalid-feedback" style="font-size:15px">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="website" style="font-family:Arial; opacity:90%; color:rgba(170, 170, 170, 0.925);">{{__('Company Website')}}</label>
                        <input class="form-control @error('website') is-invalid @enderror" id="website" name="website" placeholder="{{__('Insert Company Website')}}" type="text" style="font-family:Arial; opacity:90%; color:rgba(170, 170, 170, 0.925);"value="{{ old('website')}}">
                        @error('website')
                        <div id="validationServerUsernameFeedback" class="invalid-feedback" style="font-size:15px">{{ $message }}</div>
                        @enderror
                    </div>

                        <button class="btn btn-primary " name="submit" type="submit" style="font-family:Arial; opacity:90%;">{{__('Submit')}}</button>
                    </form>
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/companys/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    <div class="card mt-3">
        <div class="card-body">
            <div class="d-flex">
                <h1>{{__('Edit Company')}} <small class="text-muted">{{ $company->name }}</small></h1>
                <div class="ml-auto">
                    <div class="dropdown">
                        <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          {{__('Actions')}}
                        </button>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                          <a class="dropdown-item" href="{{ route('admin.companys.dashboard') }}">{{__('View Companies')}}</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item text-danger" href="#" onclick="deletecompany()">{{__('Delete Company')}}</a>
                            <form action="{{ route('admin.companys.delete', $company->id) }}" id="delete-company-form" style="display:none" method="POST">
                                @csrf
                                @method('DELETE')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{-- Update their name and email and profile image --}}
    <div class="row">
        <div class="col-md-4 offset-md-0 col-sm-8 offset-sm-2">
            {{-- Placeholder for image and option to change out just the image --}}
            <div class="card mt-3">
                <div class="card-body">
                    @if ($company->logo)
                        <img src="{{ Storage::url($company->logo) }}" style="max-width: 100%" alt="">
                    @else
                        <img src="/images/user.png" style="max-width: 100%" alt="">
                    @endif
                    <hr>
                    <button class="btn btn-outline-primary btn-sm btn-block" data-toggle="modal" data-target="#updateProfileImageModal">{{__('New Profile Image')}}</button>
                    @if ($company->logo)
                        <button class="btn btn-outline-danger btn-sm btn-block" onclick="deleteProfileImage()"><i class="fas fa-trash"></i> {{__('Delete Profile Image')}}</button>
                        <form action="{{ route('admin.companys.delete.profile-image', $company->id) }}" method="POST" id="delete-profile-image-form">
                            @csrf
                            @method('DELETE')
                        </form>
                    @endif

                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card mt-3">
                <div class="card-body">
                    <h5>{{__('Edit Company Detail')}}</h5>
                    <hr>
                    @if ($errors->count())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $message)
                                    <li>{{ $message }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form action="{{ route('admin.companys.update', $company->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="form-group">
                            <label for="">{{__('Name')}}</label>
                            <input type="text" class="form-control" name="name" value="{{ $company->name }}">
                        </div>

                        <div class="form-group">
                            <label for="">{{__('Email')}}</label>
                            <input type="email" class="form-control" name="email" value="{{ $company->email }}">
                        </div>

                        <div class="form-group">
                            <label for="">{{__('Website')}}</label>
                            <input type="website" class="form-control" name="website" value="{{ $company->website }}">
                        </div>

                        <button class="btn btn-primary float-right">{{__('Update Company')}}</button>
                    </form>
                </div>
            </div><!-- /.card company details-->

            {{-- <div class="card mt-3">
                <div class="card-body">
                    <h5>{{__('Edit Employee Detail')}}</h5>
                    <hr>
                    @if ($company->employee)
                        @include('admin.companys.employee.partials.edit-employee-form', ['company_id' => $company->id, 'employee' => $company->employee])
                    @else
                        <div class="d-flex">
                            <div class="mx-auto">
                                <a href="{{ route('admin.companys.employee.create', $company->id) }}" class="btn btn-outline-primary">{{__('Create Employee Detail')}}</a>
                            </div>
                        </div>
                    @endif
                </div>
            </div> --}}
        </div>
    </div>
</div>

<!-- Modal for updating profile image-->
<div class="modal fade" id="updateProfileImageModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{__('Update Profile Image')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('admin.companys.update.profile-image', $company->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')

                    <div class="form-group">
                        <label for="">{{__('Choose an Image')}}</label>
                        <input type="file" class="form-control-file" name="image">
                    </div>

                    <button class="btn btn-primary float-right">{{__('Update Profile Image')}}</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@push('footer-scripts')
    <script>
        function deleteProfileImage() {
            var r = confirm("Are you sure you want to delete the profile image?")

            if (r) {
                document.querySelector('form#delete-profile-image-form').submit()
            }
        }

        function deletecompany() {
            var r = confirm("Are you sure you want to delete this company? This can't be undone!")

            if (r) {
                document.querySelector('form#delete-company-form').submit()
            }
        }
    </script>
@endpush

resources/views/admin/companys/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        @if (session('success'))
            <div class="alert alert-success mt-3">
                {{ session('success') }}
            </div>
        @endif

        <div class="card mt-3">
            <div class="card-body">
                <div class="d-flex">
                    <h1>{{__('Company')}} <small class="text-muted">{{__('Showing all company')}}</small></h1>
                    <div class="ml-auto">
                        <div class="dropdown">
                            <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{__('Actions')}}
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="{{ route('admin.companys.create') }}">{{__('Create Company')}}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.card -->

        @if ($companys->count())
            {{ $companys->links() }}
            @foreach ($companys as $company)
                @include('admin.companys.partials.company-card', ['company' => $company])
            @endforeach
        @endif




                {{-- @if ($prospects->count())
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Created At</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($prospects as $prospect)
                                <tr>
                                    <td>{{ $prospect->name }}</td>
                                    <td>{{ $prospect->email }}</td>
                                    <td>{{ $prospect->pretty_created }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                @endif --}}


    </div>
@endsection