routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\Companys\CompanyEmployeesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('employee', [CompanyEmployeesController::class, 'index'])->where('employee', '[0-9]+')->name('employee.index');
Route::get('employee/create', [CompanyEmployeesController::class, 'create'])->where('employee', '[0-9]+')->name('employee.create');
Route::post('employee', [CompanyEmployeesController::class, 'store'])->where('employee', '[0-9]+')->name('employee.store');
Route::get('employee/{employee}/edit', [CompanyEmployeesController::class, 'edit'])->where('employee', '[0-9]+')->name('employee.edit');
Route::put('employee', [CompanyEmployeesController::class, 'update'])->where('employee', '[0-9]+')->name('employee.update');

Route::prefix('companys')->middleware('auth')->name('admin.companys.')->group(base_path('routes/web/companys.php'));

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class employee extends Model
{
    //use HasFactory;
    protected $table = 'company_employees';
    protected $fillable = ['first_name', 'last_name','company', 'email', 'phone'];
}

resources/views/admin/companys/employee/partials/edit-employee-form.blade.php
<form action="{{ route('admin.companys.employee.update', $employee->id) }}" method="POST">
    @csrf
    @method('PUT')

    <div class="form-group row">
        <label for="" class="col-md-3">First Name</label>
        <div class="col-md-9">
            <input type="text" class="form-control" name="first_name" value="{{ $employee->first_name }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="" class="col-md-3">Last Name</label>
        <div class="col-md-9">
            <input type="text" class="form-control" name="last_name" value="{{ $employee->last_name }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="" class="col-md-3">Company</label>
        <div class="col-md-9">
            <input type="text" class="form-control" name="company" value="{{ $employee->company }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="" class="col-md-3">Email</label>
        <div class="col-md-9">
            <input type="text" class="form-control" name="email" value="{{ $employee->email }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="" class="col-md-3">Phone</label>
        <div class="col-md-9">
            <input type="text" class="form-control" name="phone" value="{{ $employee->phone }}">
        </div>
    </div>
    <button class="btn btn-primary float-right">Update employee Details</button>
</form>

resources/views/admin/companys/employee/partials/employee-card.blade.php
<div class="card mt-3 company-card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6 col-md-8">
                <h5>{{ $company->name }}</h5>
                <ul class="list-style-none">
                    <li><strong>{{__('Email')}}:</strong> {{ $company->email}}</li>
                </ul>
            </div>
            <div class="col-sm-3 col-md-2">
                <div class="dropdown d-block">
                    <button class="btn btn-outline-secondary btn-block btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{__('Actions')}}
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{{ route('admin.companys.edit', ['company' => $company->id]) }}">{{__('Edit Company')}}</a>
                        <a class="dropdown-item" href="{{ route('admin.companys.employee.index', ['company' => $company->id]) }}">{{__('View Employee')}}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>